-- ============================================================================
-- ITRON INTELLIGENCE AGENT - Analytical Views
-- File: sql/views/05_create_views.sql
-- Description: Creates analytical views for reporting and agent consumption
-- ============================================================================

USE DATABASE ITRON_DB;
USE WAREHOUSE ITRON_WH;
USE SCHEMA ITRON_DB.ANALYTICS;

-- ============================================================================
-- View: Daily Meter Consumption Summary
-- ============================================================================
CREATE OR REPLACE VIEW V_METER_DAILY_CONSUMPTION AS
SELECT
    m.METER_ID,
    m.METER_TYPE,
    m.REGION,
    m.DISTRICT,
    m.COMMUNICATION_TYPE,
    m.DI_ENABLED,
    DATE(r.READING_TIMESTAMP) AS READING_DATE,
    r.READING_UNIT,
    COUNT(*) AS READING_COUNT,
    SUM(r.READING_VALUE) AS TOTAL_CONSUMPTION,
    AVG(r.READING_VALUE) AS AVG_CONSUMPTION,
    MAX(r.READING_VALUE) AS PEAK_CONSUMPTION,
    MIN(r.READING_VALUE) AS MIN_CONSUMPTION,
    MAX(r.DEMAND_KW) AS PEAK_DEMAND_KW,
    AVG(r.VOLTAGE) AS AVG_VOLTAGE,
    AVG(r.FLOW_RATE) AS AVG_FLOW_RATE,
    AVG(r.PRESSURE_PSI) AS AVG_PRESSURE,
    SUM(CASE WHEN r.QUALITY_FLAG = 'VALID' THEN 1 ELSE 0 END) AS VALID_READINGS,
    SUM(CASE WHEN r.QUALITY_FLAG = 'SUSPECT' THEN 1 ELSE 0 END) AS SUSPECT_READINGS,
    SUM(CASE WHEN r.TAMPER_FLAG = TRUE THEN 1 ELSE 0 END) AS TAMPER_EVENTS
FROM ITRON_DB.RAW.METERS m
JOIN ITRON_DB.RAW.METER_READINGS r ON m.METER_ID = r.METER_ID
GROUP BY m.METER_ID, m.METER_TYPE, m.REGION, m.DISTRICT, m.COMMUNICATION_TYPE, m.DI_ENABLED, DATE(r.READING_TIMESTAMP), r.READING_UNIT;

-- ============================================================================
-- View: Asset Health Scores
-- ============================================================================
CREATE OR REPLACE VIEW V_ASSET_HEALTH_SCORES AS
SELECT
    a.ASSET_ID,
    a.ASSET_TYPE,
    a.ASSET_NAME,
    a.REGION,
    a.STATUS,
    a.INSTALL_DATE,
    DATEDIFF('year', a.INSTALL_DATE, CURRENT_DATE()) AS AGE_YEARS,
    a.EXPECTED_LIFETIME_YEARS,
    ROUND(DATEDIFF('year', a.INSTALL_DATE, CURRENT_DATE()) / NULLIF(a.EXPECTED_LIFETIME_YEARS, 0) * 100, 1) AS LIFE_USED_PCT,
    a.CONDITION_SCORE,
    a.LAST_INSPECTION_DATE,
    DATEDIFF('day', a.LAST_INSPECTION_DATE, CURRENT_DATE()) AS DAYS_SINCE_INSPECTION,
    COUNT(DISTINCT wo.WORK_ORDER_ID) AS TOTAL_WORK_ORDERS,
    SUM(CASE WHEN wo.ORDER_TYPE = 'CORRECTIVE' THEN 1 ELSE 0 END) AS CORRECTIVE_ORDERS,
    SUM(CASE WHEN wo.ORDER_TYPE = 'EMERGENCY' THEN 1 ELSE 0 END) AS EMERGENCY_ORDERS,
    AVG(wo.ACTUAL_COST) AS AVG_REPAIR_COST,
    ROUND(
        a.CONDITION_SCORE * 0.4 +
        (100 - LEAST(DATEDIFF('year', a.INSTALL_DATE, CURRENT_DATE()) / NULLIF(a.EXPECTED_LIFETIME_YEARS, 0) * 100, 100)) * 0.3 +
        (100 - LEAST(COUNT(DISTINCT CASE WHEN wo.ORDER_TYPE IN ('CORRECTIVE', 'EMERGENCY') THEN wo.WORK_ORDER_ID END) * 10, 100)) * 0.3
    , 1) AS COMPOSITE_HEALTH_SCORE,
    CASE
        WHEN a.CONDITION_SCORE < 50 OR DATEDIFF('year', a.INSTALL_DATE, CURRENT_DATE()) > a.EXPECTED_LIFETIME_YEARS THEN 'CRITICAL'
        WHEN a.CONDITION_SCORE < 70 OR DATEDIFF('year', a.INSTALL_DATE, CURRENT_DATE()) > a.EXPECTED_LIFETIME_YEARS * 0.8 THEN 'AT_RISK'
        WHEN a.CONDITION_SCORE < 85 THEN 'FAIR'
        ELSE 'GOOD'
    END AS HEALTH_CATEGORY
FROM ITRON_DB.RAW.GRID_ASSETS a
LEFT JOIN ITRON_DB.RAW.WORK_ORDERS wo ON a.ASSET_ID = wo.ASSET_ID
GROUP BY a.ASSET_ID, a.ASSET_TYPE, a.ASSET_NAME, a.REGION, a.STATUS, a.INSTALL_DATE, a.EXPECTED_LIFETIME_YEARS, a.CONDITION_SCORE, a.LAST_INSPECTION_DATE;

-- ============================================================================
-- View: ESG Quarterly Summary (All Pillars)
-- ============================================================================
CREATE OR REPLACE VIEW V_ESG_QUARTERLY_SUMMARY AS
SELECT
    REPORTING_YEAR,
    REPORTING_QUARTER,
    'ENVIRONMENTAL' AS ESG_PILLAR,
    METRIC_CATEGORY,
    METRIC_NAME,
    METRIC_VALUE,
    METRIC_UNIT,
    YOY_CHANGE_PCT,
    TARGET_VALUE,
    CASE
        WHEN TARGET_VALUE IS NOT NULL AND METRIC_VALUE <= TARGET_VALUE THEN 'ON_TRACK'
        WHEN TARGET_VALUE IS NOT NULL AND METRIC_VALUE <= TARGET_VALUE * 1.1 THEN 'AT_RISK'
        WHEN TARGET_VALUE IS NOT NULL THEN 'OFF_TRACK'
        ELSE 'NO_TARGET'
    END AS PROGRESS_STATUS
FROM ITRON_DB.ANALYTICS.ESG_ENVIRONMENTAL_METRICS
UNION ALL
SELECT
    REPORTING_YEAR,
    REPORTING_QUARTER,
    'SOCIAL' AS ESG_PILLAR,
    METRIC_CATEGORY,
    METRIC_NAME,
    METRIC_VALUE,
    METRIC_UNIT,
    YOY_CHANGE_PCT,
    TARGET_VALUE,
    CASE
        WHEN TARGET_VALUE IS NOT NULL AND METRIC_NAME LIKE '%Rate%' AND METRIC_VALUE <= TARGET_VALUE THEN 'ON_TRACK'
        WHEN TARGET_VALUE IS NOT NULL AND METRIC_NAME NOT LIKE '%Rate%' AND METRIC_VALUE >= TARGET_VALUE THEN 'ON_TRACK'
        ELSE 'IN_PROGRESS'
    END AS PROGRESS_STATUS
FROM ITRON_DB.ANALYTICS.ESG_SOCIAL_METRICS
UNION ALL
SELECT
    REPORTING_YEAR,
    REPORTING_QUARTER,
    'GOVERNANCE' AS ESG_PILLAR,
    METRIC_CATEGORY,
    METRIC_NAME,
    METRIC_VALUE,
    METRIC_UNIT,
    NULL AS YOY_CHANGE_PCT,
    TARGET_VALUE,
    CASE WHEN TARGET_VALUE IS NOT NULL AND METRIC_VALUE >= TARGET_VALUE THEN 'ON_TRACK' ELSE 'IN_PROGRESS' END AS PROGRESS_STATUS
FROM ITRON_DB.ANALYTICS.ESG_GOVERNANCE_METRICS;

-- ============================================================================
-- View: Carbon Intensity by Source
-- ============================================================================
CREATE OR REPLACE VIEW V_CARBON_INTENSITY AS
SELECT
    REPORTING_YEAR,
    REPORTING_MONTH,
    SCOPE,
    EMISSION_CATEGORY,
    ENERGY_SOURCE,
    REGION,
    SUM(CO2E_METRIC_TONS) AS TOTAL_CO2E,
    SUM(CO2_METRIC_TONS) AS TOTAL_CO2,
    SUM(CH4_METRIC_TONS) AS TOTAL_CH4,
    SUM(N2O_METRIC_TONS) AS TOTAL_N2O,
    SUM(CUSTOMER_AVOIDED_EMISSIONS) AS TOTAL_AVOIDED_EMISSIONS,
    COUNT(*) AS SOURCE_COUNT
FROM ITRON_DB.ANALYTICS.CARBON_EMISSIONS
GROUP BY REPORTING_YEAR, REPORTING_MONTH, SCOPE, EMISSION_CATEGORY, ENERGY_SOURCE, REGION;

-- ============================================================================
-- View: Water Loss Analysis
-- ============================================================================
CREATE OR REPLACE VIEW V_WATER_LOSS_ANALYSIS AS
SELECT
    REPORTING_YEAR,
    REPORTING_QUARTER,
    REGION,
    SUM(WATER_SAVED_GALLONS) AS TOTAL_WATER_SAVED,
    SUM(LEAKS_DETECTED) AS TOTAL_LEAKS_DETECTED,
    SUM(LEAKS_REPAIRED) AS TOTAL_LEAKS_REPAIRED,
    ROUND(AVG(RESPONSE_TIME_HOURS), 1) AS AVG_RESPONSE_TIME,
    ROUND(AVG(NRW_PERCENTAGE), 2) AS AVG_NRW_PERCENTAGE,
    SUM(METERS_DEPLOYED) AS TOTAL_METERS_DEPLOYED,
    SUM(CUSTOMER_ALERTS_SENT) AS TOTAL_ALERTS,
    SUM(COST_SAVINGS_USD) AS TOTAL_COST_SAVINGS,
    ROUND(CASE WHEN SUM(LEAKS_DETECTED) > 0 THEN SUM(LEAKS_REPAIRED)::FLOAT / SUM(LEAKS_DETECTED) * 100 ELSE 0 END, 1) AS REPAIR_RATE_PCT
FROM ITRON_DB.ANALYTICS.WATER_CONSERVATION
GROUP BY REPORTING_YEAR, REPORTING_QUARTER, REGION;

-- ============================================================================
-- View: Grid Reliability (SAIDI/SAIFI approximation)
-- ============================================================================
CREATE OR REPLACE VIEW V_GRID_RELIABILITY AS
SELECT
    YEAR(o.START_TIME) AS OUTAGE_YEAR,
    QUARTER(o.START_TIME) AS OUTAGE_QUARTER,
    o.REGION,
    o.OUTAGE_TYPE,
    COUNT(*) AS TOTAL_OUTAGES,
    SUM(o.CUSTOMERS_AFFECTED) AS TOTAL_CUSTOMERS_AFFECTED,
    AVG(o.DURATION_MINUTES) AS AVG_DURATION_MINUTES,
    SUM(o.DURATION_MINUTES * o.CUSTOMERS_AFFECTED) AS TOTAL_CUSTOMER_MINUTES,
    ROUND(SUM(o.DURATION_MINUTES * o.CUSTOMERS_AFFECTED) / NULLIF(SUM(o.CUSTOMERS_AFFECTED), 0), 2) AS SAIDI_APPROX,
    ROUND(COUNT(*) * 1000.0 / NULLIF(SUM(o.CUSTOMERS_AFFECTED), 0), 4) AS SAIFI_APPROX,
    SUM(CASE WHEN o.CAUSE = 'WEATHER' THEN 1 ELSE 0 END) AS WEATHER_CAUSED,
    SUM(CASE WHEN o.CAUSE = 'EQUIPMENT_FAILURE' THEN 1 ELSE 0 END) AS EQUIPMENT_CAUSED,
    SUM(CASE WHEN o.CAUSE = 'PLANNED' THEN 1 ELSE 0 END) AS PLANNED_OUTAGES
FROM ITRON_DB.RAW.OUTAGE_EVENTS o
GROUP BY YEAR(o.START_TIME), QUARTER(o.START_TIME), o.REGION, o.OUTAGE_TYPE;

-- ============================================================================
-- View: SDG Alignment Scorecard with Ontology Validation
-- ============================================================================
CREATE OR REPLACE VIEW V_SDG_ALIGNMENT_SCORECARD AS
SELECT
    sp.SDG_GOAL_NUMBER,
    sp.SDG_GOAL_NAME,
    sp.SDG_TARGET,
    sp.REPORTING_YEAR,
    sp.REPORTING_QUARTER,
    sp.INDICATOR_NAME,
    sp.INDICATOR_VALUE,
    sp.INDICATOR_UNIT,
    sp.PROGRESS_STATUS,
    sp.CONTRIBUTION_TYPE,
    sm.MAPPING_STRENGTH AS ONTOLOGY_MAPPING_STRENGTH,
    sm.ESG_PILLAR AS ONTOLOGY_ESG_PILLAR,
    sm.ESG_CATEGORY AS ONTOLOGY_ESG_CATEGORY,
    sm.VALIDATION_RULE AS ONTOLOGY_RULE
FROM ITRON_DB.ANALYTICS.SDG_PROGRESS sp
LEFT JOIN ITRON_DB.ONTOLOGY.ONTOLOGY_SDG_MAPPINGS sm
    ON sp.SDG_GOAL_NUMBER = sm.SDG_GOAL_NUMBER
    AND sp.SDG_TARGET = sm.SDG_TARGET;

-- ============================================================================
-- View: Ontology Metric Catalog (Full classification reference)
-- ============================================================================
CREATE OR REPLACE VIEW V_ONTOLOGY_METRIC_CATALOG AS
SELECT
    md.DEFINITION_ID,
    md.METRIC_NAME,
    md.METRIC_DESCRIPTION,
    md.ESG_PILLAR,
    md.ESG_CATEGORY,
    md.ESG_SUBCATEGORY,
    md.STANDARD_UNIT,
    md.CALCULATION_FORMULA,
    md.REPORTING_FRAMEWORK,
    md.FRAMEWORK_INDICATOR_ID,
    md.DATA_TYPE,
    md.FREQUENCY,
    c.CLASS_NAME AS ONTOLOGY_CLASS,
    c.CLASS_URI AS ONTOLOGY_URI,
    c.HIERARCHY_LEVEL AS ONTOLOGY_DEPTH
FROM ITRON_DB.ONTOLOGY.ONTOLOGY_METRIC_DEFINITIONS md
LEFT JOIN ITRON_DB.ONTOLOGY.ONTOLOGY_CLASSES c
    ON c.ESG_PILLAR = md.ESG_PILLAR
    AND (UPPER(c.CLASS_NAME) = UPPER(md.ESG_CATEGORY)
         OR UPPER(c.CLASS_NAME) = UPPER(REPLACE(md.ESG_SUBCATEGORY, '_', '')));
