-- ============================================================================
-- ITRON INTELLIGENCE AGENT - Table Definitions
-- File: sql/setup/02_create_tables.sql
-- Description: Creates all tables across RAW, ANALYTICS, and ONTOLOGY schemas
-- ============================================================================

USE DATABASE ITRON_DB;
USE WAREHOUSE ITRON_WH;

-- ============================================================================
-- RAW SCHEMA - Operational Data
-- ============================================================================
USE SCHEMA ITRON_DB.RAW;

-- Meter Asset Registry
CREATE OR REPLACE TABLE METERS (
    METER_ID VARCHAR(50) PRIMARY KEY,
    METER_TYPE VARCHAR(20) NOT NULL COMMENT 'ELECTRIC, GAS, or WATER',
    MANUFACTURER VARCHAR(100),
    MODEL VARCHAR(100),
    FIRMWARE_VERSION VARCHAR(50),
    INSTALL_DATE DATE,
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    REGION VARCHAR(50),
    DISTRICT VARCHAR(50),
    CUSTOMER_ID VARCHAR(50),
    STATUS VARCHAR(20) DEFAULT 'ACTIVE' COMMENT 'ACTIVE, INACTIVE, MAINTENANCE, DECOMMISSIONED',
    COMMUNICATION_TYPE VARCHAR(30) COMMENT 'GEN6_MESH, GEN5_MESH, CELLULAR, RF',
    DI_ENABLED BOOLEAN DEFAULT FALSE COMMENT 'Distributed Intelligence enabled',
    LAST_COMMUNICATION TIMESTAMP_NTZ,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Interval Meter Readings
CREATE OR REPLACE TABLE METER_READINGS (
    READING_ID VARCHAR(50) PRIMARY KEY,
    METER_ID VARCHAR(50) NOT NULL,
    READING_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    READING_VALUE FLOAT NOT NULL COMMENT 'Consumption value in native units',
    READING_UNIT VARCHAR(20) NOT NULL COMMENT 'KWH, THERMS, GALLONS, CUBIC_FEET',
    INTERVAL_MINUTES INTEGER DEFAULT 15 COMMENT 'Reading interval in minutes',
    QUALITY_FLAG VARCHAR(20) DEFAULT 'VALID' COMMENT 'VALID, ESTIMATED, SUSPECT, MISSING',
    DEMAND_KW FLOAT COMMENT 'Demand in kilowatts (electric only)',
    VOLTAGE FLOAT COMMENT 'Voltage reading (electric only)',
    FLOW_RATE FLOAT COMMENT 'Flow rate (water/gas only)',
    PRESSURE_PSI FLOAT COMMENT 'Pressure reading (water/gas only)',
    TEMPERATURE_F FLOAT COMMENT 'Temperature at meter',
    TAMPER_FLAG BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- IoT Sensor Events
CREATE OR REPLACE TABLE SENSOR_EVENTS (
    EVENT_ID VARCHAR(50) PRIMARY KEY,
    SENSOR_ID VARCHAR(50) NOT NULL,
    ASSET_ID VARCHAR(50),
    EVENT_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    EVENT_TYPE VARCHAR(50) NOT NULL COMMENT 'TEMPERATURE, PRESSURE, VIBRATION, VOLTAGE, CURRENT, FLOW, HUMIDITY',
    EVENT_VALUE FLOAT NOT NULL,
    EVENT_UNIT VARCHAR(20),
    SEVERITY VARCHAR(20) DEFAULT 'NORMAL' COMMENT 'NORMAL, WARNING, CRITICAL, ALARM',
    LOCATION_LAT FLOAT,
    LOCATION_LON FLOAT,
    REGION VARCHAR(50),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Grid and Infrastructure Assets
CREATE OR REPLACE TABLE GRID_ASSETS (
    ASSET_ID VARCHAR(50) PRIMARY KEY,
    ASSET_TYPE VARCHAR(50) NOT NULL COMMENT 'TRANSFORMER, SUBSTATION, PIPE_SEGMENT, VALVE, PUMP_STATION, REGULATOR',
    ASSET_NAME VARCHAR(200),
    INSTALL_DATE DATE,
    EXPECTED_LIFETIME_YEARS INTEGER,
    MANUFACTURER VARCHAR(100),
    MODEL VARCHAR(100),
    CAPACITY_RATING FLOAT COMMENT 'Rated capacity in native units',
    CAPACITY_UNIT VARCHAR(20),
    REGION VARCHAR(50),
    DISTRICT VARCHAR(50),
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    STATUS VARCHAR(20) DEFAULT 'OPERATIONAL' COMMENT 'OPERATIONAL, DEGRADED, FAILED, MAINTENANCE',
    LAST_INSPECTION_DATE DATE,
    CONDITION_SCORE FLOAT COMMENT 'Score 0-100 from last inspection',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Work Orders and Maintenance
CREATE OR REPLACE TABLE WORK_ORDERS (
    WORK_ORDER_ID VARCHAR(50) PRIMARY KEY,
    ASSET_ID VARCHAR(50),
    METER_ID VARCHAR(50),
    ORDER_TYPE VARCHAR(50) NOT NULL COMMENT 'PREVENTIVE, CORRECTIVE, EMERGENCY, INSPECTION, INSTALL, DECOMMISSION',
    PRIORITY VARCHAR(20) NOT NULL COMMENT 'CRITICAL, HIGH, MEDIUM, LOW',
    STATUS VARCHAR(20) NOT NULL COMMENT 'OPEN, IN_PROGRESS, COMPLETED, CANCELLED',
    CREATED_DATE TIMESTAMP_NTZ NOT NULL,
    SCHEDULED_DATE DATE,
    COMPLETED_DATE TIMESTAMP_NTZ,
    TECHNICIAN_ID VARCHAR(50),
    DESCRIPTION VARCHAR(2000),
    ROOT_CAUSE VARCHAR(500),
    RESOLUTION VARCHAR(1000),
    COST_ESTIMATE FLOAT,
    ACTUAL_COST FLOAT,
    REGION VARCHAR(50),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Outage Events
CREATE OR REPLACE TABLE OUTAGE_EVENTS (
    OUTAGE_ID VARCHAR(50) PRIMARY KEY,
    OUTAGE_TYPE VARCHAR(30) NOT NULL COMMENT 'ELECTRIC, WATER, GAS',
    CAUSE VARCHAR(100) COMMENT 'WEATHER, EQUIPMENT_FAILURE, PLANNED, VEHICLE, ANIMAL, UNKNOWN',
    START_TIME TIMESTAMP_NTZ NOT NULL,
    END_TIME TIMESTAMP_NTZ,
    DURATION_MINUTES FLOAT,
    CUSTOMERS_AFFECTED INTEGER,
    REGION VARCHAR(50),
    DISTRICT VARCHAR(50),
    AFFECTED_ASSETS VARCHAR(2000) COMMENT 'Comma-separated asset IDs',
    RESTORATION_PRIORITY VARCHAR(20),
    CREW_DISPATCHED BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Utility Customer Accounts
CREATE OR REPLACE TABLE CUSTOMERS (
    CUSTOMER_ID VARCHAR(50) PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(200),
    CUSTOMER_TYPE VARCHAR(30) NOT NULL COMMENT 'RESIDENTIAL, COMMERCIAL, INDUSTRIAL, MUNICIPAL',
    SERVICE_ADDRESS VARCHAR(500),
    REGION VARCHAR(50),
    DISTRICT VARCHAR(50),
    ACCOUNT_STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    SERVICE_START_DATE DATE,
    RATE_CLASS VARCHAR(50),
    HAS_SOLAR BOOLEAN DEFAULT FALSE,
    HAS_EV BOOLEAN DEFAULT FALSE,
    HAS_BATTERY_STORAGE BOOLEAN DEFAULT FALSE,
    DEMAND_RESPONSE_ENROLLED BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- ANALYTICS SCHEMA - ESG and Analytical Data
-- ============================================================================
USE SCHEMA ITRON_DB.ANALYTICS;

-- Environmental Metrics (Quarterly)
CREATE OR REPLACE TABLE ESG_ENVIRONMENTAL_METRICS (
    METRIC_ID VARCHAR(50) PRIMARY KEY,
    REPORTING_PERIOD DATE NOT NULL COMMENT 'First day of reporting quarter',
    REPORTING_YEAR INTEGER NOT NULL,
    REPORTING_QUARTER INTEGER NOT NULL,
    METRIC_CATEGORY VARCHAR(100) NOT NULL COMMENT 'EMISSIONS, ENERGY, WATER, WASTE, BIODIVERSITY',
    METRIC_NAME VARCHAR(200) NOT NULL,
    METRIC_VALUE FLOAT NOT NULL,
    METRIC_UNIT VARCHAR(50) NOT NULL,
    SCOPE VARCHAR(20) COMMENT 'SCOPE_1, SCOPE_2, SCOPE_3 (emissions only)',
    BASELINE_VALUE FLOAT COMMENT 'Value from baseline year (2019)',
    TARGET_VALUE FLOAT COMMENT 'Annual target value',
    YOY_CHANGE_PCT FLOAT COMMENT 'Year-over-year percentage change',
    REGION VARCHAR(50) DEFAULT 'GLOBAL',
    FACILITY VARCHAR(100),
    DATA_SOURCE VARCHAR(100),
    VERIFIED BOOLEAN DEFAULT FALSE,
    VERIFIER VARCHAR(100),
    NOTES VARCHAR(2000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Social Metrics
CREATE OR REPLACE TABLE ESG_SOCIAL_METRICS (
    METRIC_ID VARCHAR(50) PRIMARY KEY,
    REPORTING_PERIOD DATE NOT NULL,
    REPORTING_YEAR INTEGER NOT NULL,
    REPORTING_QUARTER INTEGER NOT NULL,
    METRIC_CATEGORY VARCHAR(100) NOT NULL COMMENT 'WORKFORCE, HEALTH_SAFETY, COMMUNITY, SUPPLY_CHAIN, CUSTOMER_PRIVACY',
    METRIC_NAME VARCHAR(200) NOT NULL,
    METRIC_VALUE FLOAT NOT NULL,
    METRIC_UNIT VARCHAR(50) NOT NULL,
    DEMOGRAPHIC_GROUP VARCHAR(100) COMMENT 'For diversity metrics',
    REGION VARCHAR(50) DEFAULT 'GLOBAL',
    BENCHMARK_VALUE FLOAT COMMENT 'Industry benchmark',
    TARGET_VALUE FLOAT,
    YOY_CHANGE_PCT FLOAT,
    NOTES VARCHAR(2000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Governance Metrics
CREATE OR REPLACE TABLE ESG_GOVERNANCE_METRICS (
    METRIC_ID VARCHAR(50) PRIMARY KEY,
    REPORTING_PERIOD DATE NOT NULL,
    REPORTING_YEAR INTEGER NOT NULL,
    REPORTING_QUARTER INTEGER NOT NULL,
    METRIC_CATEGORY VARCHAR(100) NOT NULL COMMENT 'BOARD_DIVERSITY, COMPLIANCE, ETHICS, RISK_MANAGEMENT, TRANSPARENCY',
    METRIC_NAME VARCHAR(200) NOT NULL,
    METRIC_VALUE FLOAT NOT NULL,
    METRIC_UNIT VARCHAR(50) NOT NULL,
    TARGET_VALUE FLOAT,
    COMPLIANCE_FRAMEWORK VARCHAR(100) COMMENT 'GRI, ESRS, SASB, TCFD',
    AUDIT_STATUS VARCHAR(30),
    NOTES VARCHAR(2000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- SDG Progress Tracking
CREATE OR REPLACE TABLE SDG_PROGRESS (
    PROGRESS_ID VARCHAR(50) PRIMARY KEY,
    SDG_GOAL_NUMBER INTEGER NOT NULL COMMENT 'UN SDG Goal 1-17',
    SDG_GOAL_NAME VARCHAR(200) NOT NULL,
    SDG_TARGET VARCHAR(20) COMMENT 'Specific target (e.g., 6.1, 7.2, 13.1)',
    REPORTING_YEAR INTEGER NOT NULL,
    REPORTING_QUARTER INTEGER NOT NULL,
    INDICATOR_NAME VARCHAR(300) NOT NULL,
    INDICATOR_VALUE FLOAT,
    INDICATOR_UNIT VARCHAR(50),
    PROGRESS_STATUS VARCHAR(30) COMMENT 'ON_TRACK, AT_RISK, OFF_TRACK, ACHIEVED',
    CONTRIBUTION_TYPE VARCHAR(50) COMMENT 'DIRECT, INDIRECT, ENABLING',
    ITRON_METRIC_LINK VARCHAR(50) COMMENT 'Link to ESG metric that drives this',
    NOTES VARCHAR(2000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Carbon Emissions Detail
CREATE OR REPLACE TABLE CARBON_EMISSIONS (
    EMISSION_ID VARCHAR(50) PRIMARY KEY,
    REPORTING_PERIOD DATE NOT NULL,
    REPORTING_YEAR INTEGER NOT NULL,
    REPORTING_MONTH INTEGER NOT NULL,
    SCOPE VARCHAR(20) NOT NULL COMMENT 'SCOPE_1, SCOPE_2, SCOPE_3',
    EMISSION_SOURCE VARCHAR(200) NOT NULL COMMENT 'Specific source category',
    EMISSION_CATEGORY VARCHAR(100) COMMENT 'STATIONARY_COMBUSTION, MOBILE, PURCHASED_ELECTRICITY, etc.',
    CO2E_METRIC_TONS FLOAT NOT NULL,
    CO2_METRIC_TONS FLOAT,
    CH4_METRIC_TONS FLOAT,
    N2O_METRIC_TONS FLOAT,
    ENERGY_SOURCE VARCHAR(50) COMMENT 'NATURAL_GAS, DIESEL, ELECTRICITY, RENEWABLE',
    FACILITY VARCHAR(100),
    REGION VARCHAR(50),
    CALCULATION_METHOD VARCHAR(50) COMMENT 'MEASURED, CALCULATED, ESTIMATED',
    EMISSION_FACTOR FLOAT,
    EMISSION_FACTOR_SOURCE VARCHAR(100),
    CUSTOMER_AVOIDED_EMISSIONS FLOAT COMMENT 'Emissions avoided by Itron solutions',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Water Conservation Metrics
CREATE OR REPLACE TABLE WATER_CONSERVATION (
    RECORD_ID VARCHAR(50) PRIMARY KEY,
    REPORTING_PERIOD DATE NOT NULL,
    REPORTING_YEAR INTEGER NOT NULL,
    REPORTING_QUARTER INTEGER NOT NULL,
    METRIC_TYPE VARCHAR(100) NOT NULL COMMENT 'NON_REVENUE_WATER, LEAK_DETECTION, CONSUMPTION_REDUCTION, RECYCLING',
    REGION VARCHAR(50),
    WATER_SAVED_GALLONS FLOAT,
    LEAKS_DETECTED INTEGER,
    LEAKS_REPAIRED INTEGER,
    RESPONSE_TIME_HOURS FLOAT COMMENT 'Average time to repair',
    NRW_PERCENTAGE FLOAT COMMENT 'Non-revenue water as percentage of total',
    METERS_DEPLOYED INTEGER COMMENT 'Smart water meters active',
    CUSTOMER_ALERTS_SENT INTEGER,
    COST_SAVINGS_USD FLOAT,
    NOTES VARCHAR(2000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Energy Efficiency Metrics
CREATE OR REPLACE TABLE ENERGY_EFFICIENCY (
    RECORD_ID VARCHAR(50) PRIMARY KEY,
    REPORTING_PERIOD DATE NOT NULL,
    REPORTING_YEAR INTEGER NOT NULL,
    REPORTING_QUARTER INTEGER NOT NULL,
    METRIC_TYPE VARCHAR(100) NOT NULL COMMENT 'GRID_LOSS, DEMAND_RESPONSE, PEAK_REDUCTION, DER_INTEGRATION, VOLTAGE_OPTIMIZATION',
    REGION VARCHAR(50),
    ENERGY_SAVED_MWH FLOAT,
    PEAK_REDUCTION_MW FLOAT,
    GRID_LOSS_PERCENTAGE FLOAT,
    DER_CAPACITY_MW FLOAT COMMENT 'Distributed Energy Resources managed',
    DEMAND_RESPONSE_MW FLOAT COMMENT 'Flexible load dispatched',
    VOLTAGE_OPTIMIZATION_SAVINGS_MWH FLOAT,
    ENDPOINTS_MANAGED INTEGER,
    COST_SAVINGS_USD FLOAT,
    CO2E_AVOIDED_TONS FLOAT,
    NOTES VARCHAR(2000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ESG Documents (for Cortex Search)
CREATE OR REPLACE TABLE ESG_DOCUMENTS (
    DOCUMENT_ID VARCHAR(50) PRIMARY KEY,
    TITLE VARCHAR(500) NOT NULL,
    CONTENT VARCHAR(16000000) NOT NULL COMMENT 'Full document text content',
    DOCUMENT_TYPE VARCHAR(50) NOT NULL COMMENT 'SUSTAINABILITY_REPORT, POLICY, FRAMEWORK, PRESS_RELEASE, CASE_STUDY',
    ESG_PILLAR VARCHAR(30) COMMENT 'ENVIRONMENTAL, SOCIAL, GOVERNANCE, ALL',
    SDG_GOAL VARCHAR(50) COMMENT 'Related SDG goals',
    YEAR INTEGER,
    SOURCE VARCHAR(200),
    AUTHOR VARCHAR(200),
    PUBLISHED_DATE DATE,
    TAGS VARCHAR(1000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- ONTOLOGY SCHEMA - ESGOnt Ontology Tables
-- ============================================================================
USE SCHEMA ITRON_DB.ONTOLOGY;

-- OWL Classes from ESGOnt
CREATE OR REPLACE TABLE ONTOLOGY_CLASSES (
    CLASS_ID VARCHAR(100) PRIMARY KEY,
    CLASS_NAME VARCHAR(200) NOT NULL,
    CLASS_URI VARCHAR(500) NOT NULL,
    PARENT_CLASS_ID VARCHAR(100) COMMENT 'Direct superclass',
    ESG_PILLAR VARCHAR(30) COMMENT 'ENVIRONMENTAL, SOCIAL, GOVERNANCE',
    HIERARCHY_LEVEL INTEGER COMMENT 'Depth in class tree (0=root)',
    DESCRIPTION VARCHAR(2000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Object and Data Properties
CREATE OR REPLACE TABLE ONTOLOGY_PROPERTIES (
    PROPERTY_ID VARCHAR(100) PRIMARY KEY,
    PROPERTY_NAME VARCHAR(200) NOT NULL,
    PROPERTY_URI VARCHAR(500) NOT NULL,
    PROPERTY_TYPE VARCHAR(20) NOT NULL COMMENT 'OBJECT or DATA',
    DOMAIN_CLASS_ID VARCHAR(100) COMMENT 'Class this property belongs to',
    RANGE_CLASS_ID VARCHAR(100) COMMENT 'Class this property points to (object) or datatype (data)',
    DESCRIPTION VARCHAR(2000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Class-to-Class Relationships (subClassOf, equivalentClass, etc.)
CREATE OR REPLACE TABLE ONTOLOGY_RELATIONSHIPS (
    RELATIONSHIP_ID VARCHAR(100) PRIMARY KEY,
    SOURCE_CLASS_ID VARCHAR(100) NOT NULL,
    TARGET_CLASS_ID VARCHAR(100) NOT NULL,
    RELATIONSHIP_TYPE VARCHAR(50) NOT NULL COMMENT 'SUBCLASS_OF, EQUIVALENT_TO, DISJOINT_WITH, PART_OF',
    PROPERTY_ID VARCHAR(100) COMMENT 'The property defining this relationship',
    DESCRIPTION VARCHAR(2000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ESG Metric to SDG Mapping (Deterministic Rules)
CREATE OR REPLACE TABLE ONTOLOGY_SDG_MAPPINGS (
    MAPPING_ID VARCHAR(100) PRIMARY KEY,
    ESG_METRIC_NAME VARCHAR(200) NOT NULL,
    ESG_PILLAR VARCHAR(30) NOT NULL,
    ESG_CATEGORY VARCHAR(100) NOT NULL,
    SDG_GOAL_NUMBER INTEGER NOT NULL,
    SDG_GOAL_NAME VARCHAR(200) NOT NULL,
    SDG_TARGET VARCHAR(20),
    SDG_INDICATOR VARCHAR(50),
    MAPPING_STRENGTH VARCHAR(20) NOT NULL COMMENT 'DIRECT, STRONG, MODERATE, INDIRECT',
    VALIDATION_RULE VARCHAR(2000) COMMENT 'Rule description for constraint validation',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Validation Rules for LLM Constraint
CREATE OR REPLACE TABLE ONTOLOGY_VALIDATION_RULES (
    RULE_ID VARCHAR(100) PRIMARY KEY,
    RULE_NAME VARCHAR(200) NOT NULL,
    RULE_TYPE VARCHAR(50) NOT NULL COMMENT 'CLASSIFICATION, UNIT, SDG_ALIGNMENT, HIERARCHY, THRESHOLD',
    RULE_CATEGORY VARCHAR(100) NOT NULL COMMENT 'The ESG category this rule applies to',
    CONDITION_FIELD VARCHAR(200) NOT NULL COMMENT 'The field/metric being validated',
    EXPECTED_VALUE VARCHAR(500) NOT NULL COMMENT 'The correct/expected value or pattern',
    ERROR_MESSAGE VARCHAR(1000) NOT NULL COMMENT 'Message when validation fails',
    SEVERITY VARCHAR(20) DEFAULT 'ERROR' COMMENT 'ERROR, WARNING, INFO',
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Standard Metric Definitions with Units
CREATE OR REPLACE TABLE ONTOLOGY_METRIC_DEFINITIONS (
    DEFINITION_ID VARCHAR(100) PRIMARY KEY,
    METRIC_NAME VARCHAR(200) NOT NULL,
    METRIC_DESCRIPTION VARCHAR(2000) NOT NULL,
    ESG_PILLAR VARCHAR(30) NOT NULL,
    ESG_CATEGORY VARCHAR(100) NOT NULL,
    ESG_SUBCATEGORY VARCHAR(100),
    STANDARD_UNIT VARCHAR(50) NOT NULL,
    CALCULATION_FORMULA VARCHAR(1000),
    REPORTING_FRAMEWORK VARCHAR(100) COMMENT 'GRI, ESRS, SASB, TCFD, CDP',
    FRAMEWORK_INDICATOR_ID VARCHAR(50) COMMENT 'Standard indicator code (e.g., GRI 305-1)',
    DATA_TYPE VARCHAR(30) DEFAULT 'QUANTITATIVE' COMMENT 'QUANTITATIVE, QUALITATIVE, BINARY',
    FREQUENCY VARCHAR(20) DEFAULT 'QUARTERLY' COMMENT 'ANNUAL, QUARTERLY, MONTHLY',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
